### ISSUE TITLE
ddt4all on a Mac?

### ISSUE THREAD

**Issue by pyromixer** [cedricp/ddt4all#122]
Does anyone have a step by step guide to install ddt4all directly on the Mac?

And how can I create a startfile on the Mac so that I can start ddt4all without the terminal?

THX

**Comment by cedricp** [comment]
A user told me it's working. You need to install Python and PyQt4 or PyQt5 and launch it from the terminal : 
pythonw ddt4all.py
About desktop shortcut, I have no experience with Mac Os, but I'm sure it's not a big deal.

**Comment by shrlnm** [comment]
For starting without terminal write a simple script for example with name  start.sh 
`
#!/bin/bash
cd ~/ddt4all-master
/usr/bin/env python ddt4all.py
`
Where "~/ddt4all-master" is a path to ddt4all folder
Place this script on a Desktop and then do as in this topic 
https://stackoverflow.com/questions/5125907/how-to-run-a-shell-script-in-os-x-by-double-clicking/29710607

**Comment by bjthenextstep** [comment]
> A user told me it's working. You need to install Python and PyQt4 or PyQt5 and launch it from the terminal :
> pythonw ddt4all.py
> About desktop shortcut, I have no experience with Mac Os, but I'm sure it's not a big deal.

@cedricp as you said, install Python and PyQt4 or PyQt5.
I installed Python and PyQt5 on MacOS 10.14.3 and when launching from the terminal always got this following error message:
Traceback (most recent call last):
  File "ddt4all.py", line 23, in <module>
    import PyQt4.QtGui as gui
ImportError: No module named PyQt4.QtGui

Should I install as well PyQt4 ?
Thank you for your help.

**Comment by shrlnm** [comment]
@bjthenextstep 
Yes, you need pyqt4 and latest version of python@2

you may install them by brew

brew install python@2
brew install cartr/qt4/pyqt

then run the ddt4all.py by the appropriate python 
cd ~/ddt4all-master
/usr/bin/env python ddt4all.py

**Comment by shrlnm** [comment]
![Screenshot 2019-03-13 at 09 00 53](https://user-images.githubusercontent.com/16278412/54256910-992b9480-456e-11e9-8993-52fd8a2f345c.png)

**Comment by bjthenextstep** [comment]
@shrlnm 
Thank you for your help and resolved.

**Comment by Virallata** [comment]
Hello, i installed python, PyQt4 PyQt5 and still got this error:

Kaues-MacBook-Air:ddt4all-master kaue$ /usr/bin/env python ddt4all.py
Traceback (most recent call last):
  File "ddt4all.py", line 24, in <module>
    import PyQt4.QtGui as gui
ImportError: No module named sip

**Comment by warwintryborn** [comment]
Hi @Virallata 

Did you resolve the problem? I`m with the same issue. I installed pyqt through brew and still had the issue.

**Comment by warwintryborn** [comment]
@shrlnm Can you help me with this problem?

**Comment by vildhjarta8** [comment]
@Virallata @warwintryborn 

Ok, guys, I will try to help you since faced the same issue.
First of all, you should download and build the sip by yourself.

Download the SIP v4 archive here: https://riverbankcomputing.com/software/sip/download and extract it.
Open terminal and run:
```bash
cd /path/to/sip-4.19.24
python configure.py
make
make install
```
It will build and install the SIP.

If you are getting the error "Operation not permitted" after `make install`, you should disable System Integrity Protection.
Reboot your Mac, hold Command + R to enter Recovery Mode.
In Recovery Mode, open the terminal and run `csrutil disable` then reboot again.
If you're running macOS Catalina you should run in additional:
```bash
sudo mount -uw /
killall Finder
```
Then, open the terminal again, cd into folder with extracted SIP and run `make install` again. 
Now you can run ddt4all via `python /path/to/ddt4all.py`.

Don't forget to reboot to recovery and activate the system integrity protection again using `csrutil enable`.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/2393640/94067343-65cdf500-fdf6-11ea-9cbb-ebebd020d52e.png">

**Comment by smail2133** [comment]
On BigSur this issue still exists.

**Comment by toek79** [comment]
Maybe my short guide how to install DDT4ALL on MacBooks can be useful for somebody:
( It works on Intel and ARM64. For ARM64 brew is using Rosetta emulation mode )

- Open the console terminal
- Install brew channel and packages:
   Intel: 
             /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
             brew install qt@5
             brew install pyqt@5
   ARM64:
             cd /usr/local 
             sudo mkdir homebrew 
             sudo chmod 777 homebrew
             curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
             arch -x86_64 /usr/local/homebrew/bin/brew install qt@5
             arch -x86_64 /usr/local/homebrew/bin/brew install pyqt@5
- Run DDT4ALL
   Intel:
             python3 ddt4all.py
   ARM64:
             /usr/local/homebrew/bin/python3 ddt4all.py
- Hack your car ;-)

**Comment by msrdrakyz** [comment]
hello  i just started using macos and i need to run this program can someone help me

**Comment by Furtif** [comment]
work in mac... https://github.com/cedricp/ddt4all/issues/836
