### ISSUE TITLE
Activation LKA Scenic IV

### ISSUE THREAD

**Issue by Banana009** [cedricp/ddt4all#35]
Did anyone activate LKA  (Lane-Keeping Assist ) or DW  (distance warning) or ACC ( Adaptive Cruise Control )?  I have Hands Free Parking so I have all the components . I am not able to activate LKA.  I set it in RadNav2.3 and then XFA_RACam_v3.7 - LKA.LKA_Configuration_Status. Function is active in Rlink2 menu, but does not work physically, side arrows are not green. Maybe it has to be activated  in A-IVI_v0.9 .?  A-IVI_v0.9 does not communicate with ECUs :-(

**Comment by ohayyam** [comment]
You are at wrong way brother. You can try to activate "LDW | Lane Departure Warning System"  not LKA. My Talisman LDW working and i am trying to activate LKA which is different than LDW.  LDW just warning with sound and visual but LKA should keep car between lanes.

**Comment by Banana009** [comment]
Why wrong way? New Scenic IV  has LDW and LKA. Talisman has only LDW.  
http://ie.e-guide.renault.com/eng/New-Scenic/LANE-KEEPING-ASSIST

**Comment by ohayyam** [comment]
Talisman also have hands free parking and have all components and LKA can be activated thats why we are using DDT4All rigth ? I may miss undestand when u wrote side arrows not green means your LDW also not working rigth ? Thats why you are on wrong way. First u have to try to activate LDW then u can continue to try for LKA. I think if LDW not works LKA will not works...

**Comment by Banana009** [comment]
Talisman has different components that do not allow LKA. Only new Scenic has LKA because it has a vibrating wheel. (haptic LKA) . 
I have active LDW but LKA is deactivated (the region rules) . See attach. the side arrows are still gray 
![img_2030](https://user-images.githubusercontent.com/35255691/36026630-df6f4314-0d8f-11e8-8548-4487dc8aebbb.JPG)

**Comment by ohayyam** [comment]
I see.. Did you check this screen :)
![lka ldw](https://user-images.githubusercontent.com/35384108/36030445-516872a6-0db8-11e8-9afe-43216f3f0f28.jpeg)

**Comment by Banana009** [comment]
Unfortunately it does not work. WRONG RESPONSE , see: 
![lka_ldw](https://user-images.githubusercontent.com/35255691/36075930-a76cf138-0f55-11e8-9f16-81eb5385c788.JPG)

**Comment by cedricp** [comment]
Is your ECU auto detected with the scan button ? You probably are using the wrong file

**Comment by Banana009** [comment]
This file is for Scenic IV, is not it true? Maybe LOW-HIGH can problem?

**Comment by cedricp** [comment]
There are several files depending on the ECU software version and vehicles options. You should only use those that are detected by the scanner. For example, the injection unit is not the same if the engine is diesel or gasoline.

**Comment by Banana009** [comment]
I will try it. Where áre updates of ECUs  .xml files ?

**Comment by cedricp** [comment]
As indicated on the **readme** file, you must own that copyrighted database of xml files.

**Comment by Banana009** [comment]
There is a problem that there are many files and nobody knows what they are doing.

**Comment by cedricp** [comment]
Sorry, but this software is not an easy way to tune your vehicle, it's an engineer tool that needs some experience and study.

**Comment by ynkpars63** [comment]
Hello 
there. my agent is using MeganE 4th program for a long time. In the program I could not find a section about the mirrors automatically falling back to the mirrors of the mirrors. I have a feature like this in talisman models and I am sure it is in ECU but I can not find it. I am very happy to help you with the subject.

**Comment by Banana009** [comment]
The problem solved, . You only have to press the start button but not the pedals!! After that, I am able to write to CMF1_REPS.

**Comment by tomka1118** [comment]
Please help me, I've made all the settings that you wrote here but doens't work for me.

Can I reset some of the devices over DDT4All to start working?

**Comment by Banana009** [comment]
Every time you start the engine, you must turn the LKA manually from the R-link screen, otherwise it does not work :-(

**Comment by tomka1118** [comment]
I'm new in this busienss.

Idon't have the selection possibility in the menu of LKA/LDW menu, only have the basic settings (Haptic level and strongness)

Could you write down a Quick guide?

**Comment by Banana009** [comment]
It is very dangerous, if you do not have enough knowledge, it can damage the vehicle.
Are you able to read and write to ECUs?

**Comment by tomka1118** [comment]
yes I can. 


I'm an IT guy with electrician PhD.


I bought a really good ELM 327 adapter witg original ELM chip.


So there can't be any problem.

**Comment by tomka1118** [comment]
Have you tried to enable the R-sound option? it is working on Scenic 4 ?

**Comment by tomka1118** [comment]
I made it! Don't know how but a made all the settings again and restarted the R-Link 2 and it worked.

I have the Screen Mirroring and the working LKA/LDW menu.

I also enabled all the functions thru driving. It works too.

I enabled the R-Sound but didn't appear the menu option. I have look after.

**Comment by Banana009** [comment]
GOOD work, you have to reset R-link after avery change( long press start button for more then 10 sec) There are 3 types of reset, be carefull:
"Hard Reset" simulates a shutdown of the power supply.
"key off on Reset" simulates the drain and turn on the ignition with the key.
"Soft Reset" allows initialization of certain program units and their storage structures.
R-sound allows to add additional sound (Alpine), It works for me (Intense) , but I read that BOSE cars do not work. :-(

**Comment by tomka1118** [comment]
Thanks,

I'm not in love with this new Bose, in my opinoin the sound in SCIII was better than actual.

This microphone volume level setting has more disadvantages and less advantage.

Wbr

**Comment by Banana009** [comment]
I did not want BOSE because it has a large amp in the storage space :-(

**Comment by tomka1118** [comment]
Why could they fit the complete amplifier under the passenger's seat in the SCIII? 

The actual has a "boom-box" sound and I don't like it. Nor my child in the second row...

**Comment by payamt20** [comment]
Hello,
how I can active auto closure of sunroof and windows for talisman by DDT4all?
Please guide me. Thanks

**Comment by tomka1118** [comment]
I don't know the Talisman. But.

First of all you have to have the initial package:
 - a good ELM (USB or Wifi),
 - this program (DDT4All) and the corresponding database (ecus.txt)

 When all you have, you should test your ELM compatibility, because a bad/fake ELM can destroy your cars ECU and all others...

If you don't know what do you want to change, first learn to use the DDT4all in the "Edit mode".

I found only one corresponding setup point, it is in the Audio/RadNav 2.3/Configuration/ECU Part II. Then name what I think it could be: HMI/Settings/ Auto lock up.

But it could be maybe the auto door closing?? Have to try.

In my Scenic IV (like the old one SCIII) if I push the closing button on the drivers door twice, all the windows come up.

Wbr,

**Comment by SorakCz** [comment]
Hi tomka1118,
I am interesting about switch on LKA. I have GS IV Bose. Do you know if you lost warranty by this adjustment? Could you please share some video how it work?
Thank you

**Comment by Banana009** [comment]
Also, I think the service center does not recognize change settings. I think ECU does not record changes. You can always change your settings backwards.
After each diagnosis by an authorized service center, the settings will be reset to factory settings (here in Czech Republic).
Unfortunately this LKA does not hold the car in the middle of the lane but only changes the steering when the vehicle detects a line. It looks like ping ping. Do you understand me? Other car makers can keep a vehicle in the middle of a lane (VW, Skoda), unfortunately Renault does not. LKA only helps in critical situations. What is uncomfortable that you must activate the LKA after each engine start.

**Comment by payamt20** [comment]
Hello,
Where I can find Unlocking video playing while driving in Talisman.
Thanks


Sent from Yahoo Mail for iPhone


On Saturday, May 19, 2018, 1:51 AM, tomka1118 <notifications@github.com> wrote:


I don't know the Talisman. But.

First of all you have to have the initial package:
   
   - a good ELM (USB or Wifi),
   - this program (DDT4All) and the corresponding database (ecus.txt)

When all you have, you should test your ELM compatibility, because a bad/fake ELM can destroy your cars ECU and all others...

If you don't know what do you want to change, first learn to use the DDT4all in the "Edit mode".

I found only one corresponding setup point, it is in the Audio/RadNav 2.3/Configuration/ECU Part II. Then name what I think it could be: HMI/Settings/ Auto lock up.

But it could be maybe the auto door closing?? Have to try.

In my Scenic IV (like the old one SCIII) if I push the closing button on the drivers door twice, all the windows come up.

Wbr,

**Comment by bostu** [comment]
Hello to all, 
not to open new post I would rather ask here.

do you think that LKA is possible in Espace V 2016... I also have Park assist and LDW by default.

When I look in catalogs for new talisman or espace there is no posibility to buy LKA in any version of the car.... it is only possibe as I see for 200€ at Scenic models. 

Did anyone try to activate on espace?

Thank you for the answers

**Comment by Banana009** [comment]
Bad news for you, you never activate LKA on the Espace. You don't have RaCam, which calculates the trajectory.  Unfortunately, even on Koleus with RaCam, LKA cannot be activated because it has a different type of software.
Only the new Scenic IV can and the new Clio probably ...

**Comment by bostu** [comment]
Thank you for the infolp Boštjan 
-------- Izvirno sporočilo --------Od: Banana009 <notifications@github.com> Datum: 25. 4. 19  08:57  (GMT+01:00) Za: cedricp/ddt4all <ddt4all@noreply.github.com> Kp: bostu <bostjan.stucin@gmail.com>, Comment <comment@noreply.github.com> Zadeva: Re: [cedricp/ddt4all] Activation LKA Scenic IV (#35) Bad news for you, you never activate LKA on the Espace. You don't have RaCam, which calculates the trajectory.  Unfortunately, even on Koleus with RaCam, LKA cannot be activated because it has a different type of software.
Only the new Scenic IV can and the new Clio probably ...

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cedricp/ddt4all","title":"cedricp/ddt4all","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cedricp/ddt4all"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Banana009 in #35: Bad news for you, you never activate LKA on the Espace. You don't have RaCam, which calculates the trajectory.  Unfortunately, even on Koleus with RaCam, LKA cannot be activated because it has a different type of software.\r\nOnly the new Scenic IV can and the new Clio probably ..."}],"action":{"name":"View Issue","url":"https://github.com/cedricp/ddt4all/issues/35#issuecomment-486543840"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cedricp/ddt4all/issues/35#issuecomment-486543840",
"url": "https://github.com/cedricp/ddt4all/issues/35#issuecomment-486543840",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bostu** [comment]
hello again

can I just ask you what kind of OBDII adapter do you use?

Thank you

**Comment by ustunkaya07** [comment]
And what about LKA for megane 4? I have LDW, auto brake, Self parking etc. İs there any way to activate it?

**Comment by scoobydoo511** [comment]
If you have all off those in your car, then you are probably able to activate LKA...

**Comment by Dema323** [comment]
Did you find where you activate LKA for megane iv ?

**Comment by ustunkaya07** [comment]
Unfortunately no, dude. Megane 4 and scenic 4 have different hardwares. To activate LKA, car Must have haptic steering wheel. Megane 4 has not :( the problem is depend on hardware, it seems

**Comment by Dema323** [comment]
![image](https://user-images.githubusercontent.com/25054469/84687101-73452a80-af3d-11ea-97dc-714d5e7e3244.png)
Just found this though

**Comment by Banana009** [comment]
It is not possible to activare LKA on Megane. There is not Racam.

**Comment by Dema323** [comment]
Well it can do ldw so don't see why lka wouldn't be possible.

**Comment by ustunkaya07** [comment]
It does not make sense . There are radar, self parking, adaptive criuse control in Car. There are radar and all sensors but cannot activate LKA. There must be a way.

**Comment by Banana009** [comment]
There is no chance to activate LKA on Megane because you do not have RaCam. The RaCam unit calculates the LKA. Buy a new car, Megane phase 2. :-)

**Comment by Dema323** [comment]
And why is the racam not needed for ldw ?

**Comment by micdesa** [comment]
Hi Guys, do you have any news about activating LKA on Megane IV? It's very strange that there are no wau to do it.
Thanks.

**Comment by AndyIreland** [comment]
> Hi Guys, do you have any news about activating LKA on Megane IV? It's very strange that there are no wau to do it.
> Thanks.

what have you got a Ph2 Megane? there is a setting in navigation any help ? you most probably need extra hardware like camera in the windscreen if you havent already got it, and specially wired OBD2 cable or adaptor so you can read / write multimedia and OBD2 to not be secured by gateway 

![lka megane](https://user-images.githubusercontent.com/49172217/126086671-8ff3ad92-c869-44b5-98d3-77a099f617d4.jpg)

**Comment by micdesa** [comment]
Hi,
I have Megane Ph 1 Bose version...

**Comment by AndyIreland** [comment]
what ECU does it find when you search with the magnifying glass in DDT4ALL? (you may need the specially wired OBD2 adaptor or cable to read the multimedia parameters through the CAN network)

**Comment by AdameikoMaxim** [comment]
Sorry for asking again, but is it still no chance to activate for Megane 4 Ph 1? Even for Intens having all others assistants

**Comment by AndyIreland** [comment]
> Sorry for asking again, but is it still no chance to activate for Megane 4 Ph 1? Even for Intens having all others assistants

So, i am predicting you have the easylink radio system and the OBD2 has got the security gateway block on it - if you have the camera for the LKA the setting is more than likely there in DDT4all but the security gateway has to be unlocked to make any changes

**Comment by AndyIreland** [comment]
> > Sorry for asking again, but is it still no chance to activate for Megane 4 Ph 1? Even for Intens having all others assistants
> 
> So, i am predicting you have the easylink radio system and the OBD2 has got the security gateway block on it - if you have the camera for the LKA the setting is more than likely there in DDT4all but the security gateway has to be unlocked to make any changes - even then I am not sure after unlocking what is needed to change parameters on the easylink - on the rlink1 &2 you had to solder up some pins on the elm327 to read/write CAN-H  but I dont really know on the newer Renaults  with the security gateway if you still need to do that now or how you read/write to the easylink sorry

**Comment by alquistus** [comment]
@Banana009 Hi, you wrote that it is impossible to activate LKA on Espace V ph1, because of HW. But is it possible to find RACam or steering wheel from Scenic for example and activate LKA?

**Comment by gonzaloalbito** [comment]
I'm about to buy an Espace V from 2016. It lacks ACC and LDW. It has emergency brake assist and park assist so I'm not sure it has all needed sensors (cameras and proximity sensor) to enable LDW and ACC after buying it, or it will not be possible at all. Could anyone help me?
