### ISSUE TITLE
#MEGANE IV door locking from inside 

### ISSUE THREAD

**Issue by eminpolat85** [cedricp/ddt4all#555]
Is this possible with ddt4all ?

**Comment by BillyJacobie** [comment]
> Is this possible with ddt4all ?

Please forgive if I misunderstood your question, but
Have you tried pressing and holding lock button for 3-5 seconds, this turns "Auto Door Lock ON/OFF"?

![image](https://user-images.githubusercontent.com/20990987/114287239-c1479380-9a65-11eb-9e29-f747101791c2.png)

**Comment by eminpolat85** [comment]
It locks against the outside but Iwant it to open from the inside. Thank you for your interest

**Comment by tomidix** [comment]
This is not possible because it would be a safety issue. If that would be possible someone would be able to trap a person inside a vehicle. As this scenario is not acceptable -> this is not possible. 

However if your vehicle is fitted with superlock (countries where this is allowed), you would be able to lock it from outside the vehicle and then in case of the broken window, thief won't be able to open the doors from inside. This requires special module and if it's fitted the setting is already turned on. Locking the car with double click invokes it.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
