### ISSUE TITLE
Maybe it is a time to create new release?

### ISSUE THREAD

**Issue by igogo2** [cedricp/ddt4all#805]
Latest v2.0 doesn't work correctly.

**Comment by AndyIreland** [comment]
try visiting here for updates?
https://github.com/Furtif/ddt4all

**Comment by igogo2** [comment]
Try to count how many commits is there https://github.com/cedricp/ddt4all/commits/master since Nov 10, 2020.

**Comment by igogo2** [comment]
@cedricp

**Comment by igogo2** [comment]
How i can run the application? What i do wrong?
![ddt4all](https://user-images.githubusercontent.com/6361239/230793464-7a169c7f-9313-4da6-abd7-998e487319b7.png)

**Comment by AndyIreland** [comment]
if you are trying to run the DDT4ALL for windows Application and you want one with a built in database and desktop icon use this one: 
https://www.drive2.ru/b/498093336985338243/

**Comment by igogo2** [comment]
Thanks. But i want to run the newest version on Python 3. Not from 2019 year.

**Comment by AndyIreland** [comment]
> Thanks. But i want to run the newest version on Python 3. Not from 2019 year.

why? :) 
 if it does what you want it to do and finds the right ECU's parameters that you want to change?
 
 There is another workaround if you want to have up to date and i think this will work , you can download from Drive 2 so that you have the database and the desktop icon then go to furtive updates on github and download all the files then go to your program files/ddt4all folder and paste the up to date files over-writing the files ... I think that will work

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
