### ISSUE TITLE
Disable SOS call 

### ISSUE THREAD

**Issue by Tony2k** [cedricp/ddt4all#828]
I replaced the original radio of the Dacia Spring with a generic one (non-can) and now the writing "check sos call" appears on the panel.  Why does the call have to go through the radio if it is not equipped with GPS or a telephone module?  Is it possible to disable this function with ddt4all?

**Comment by AndyIreland** [comment]
could be if you can unlock the security gateway (if its got one) with a token, and then do a search in DDT4all and if it finds 'Clustre' look on settings and see if you can turn off the SOS message on the dash

**Comment by Tony2k** [comment]
Do you mean "cluster"?

**Comment by KarelSvo** [comment]
TCU DataWrite.Ecall Activation Status
Reg Ecall activated to Reg Ecall deactivated

**Comment by Tony2k** [comment]
> TCU DataWrite.Ecall Activation Status Reg Ecall activated change to Reg Ecall deactivated Cluster DataWrite.TCU_EcallPresent_CF With Emergency_Call change to Without Emergency_Call

Can you explain me please where is DataWrite.Ecall Activation Status?

![Spring](https://github.com/cedricp/ddt4all/assets/16784561/51c37c4e-6aec-4efc-bdb1-def937ed5fe7)

**Comment by AndyIreland** [comment]
in my Renault Zoe EV there is some ecall settings in the rlink1 medianav MFD  settings:  I couldnt say where it is on your dacia spring . Maybe in the easylink radio or whatever you have? 

![image](https://github.com/cedricp/ddt4all/assets/49172217/b0397bc4-c156-471c-938f-9f3433fcbc53)

**Comment by KarelSvo** [comment]
TCU_AIVC_v2.27/CONFIGURATION/Reg Ecall 1/Ecall Activation Status  Line number 6

**Comment by Tony2k** [comment]
How solved the problem working on DTC Activation Status:

![Spring](https://github.com/cedricp/ddt4all/assets/16784561/c001290b-3500-446f-ba5e-0e8e9e3e5ece)

**Comment by rxtarcher** [comment]
Hello, I got exactly the same message "Check SOS Call".

I am trying to go through ddt4all in order to deactivate "Aux-In Info/Tel-Mute-Output" and "Virgin Configuration", but it doesn't work. I press the "Einstein" button in order to activate expert mode and change the value from "Activated" to "Deactivated", I press "Write activation status of DTC" and then "Key On/Off Reset" but nothing happens. If I refresh or close and open ddt4all both options are still "Activated". 
Also, in the "Read" right column, I can't see if an option is "Activated" or "Deactivated", they are all write "NO DATA".

Do you know what do I have to do in order to be able to deactivate both options?

Thank you.
